CREATE TABLE IF NOT EXISTS users(
 id BIGSERIAL PRIMARY KEY,
 email VARCHAR(255) UNIQUE NOT NULL,
 hashed_password TEXT NOT NULL,
 role VARCHAR(30) NOT NULL DEFAULT 'student'
);
CREATE TABLE IF NOT EXISTS concepts(
 id BIGSERIAL PRIMARY KEY,
 title VARCHAR(200) NOT NULL,
 content TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS learning_progress(
 id BIGSERIAL PRIMARY KEY,
 user_id BIGINT REFERENCES users(id),
 concept_id BIGINT REFERENCES concepts(id),
 mastery DOUBLE PRECISION NOT NULL DEFAULT 0
);
